branch-defaults:
  default:
    environment: django-env
environment-defaults:
  django-env:
    branch: null
    repository: origin
global:
  application_name: django-tutorial
  branch: null
  default_ec2_keyname: Tejas
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
